name: Link check

on:
  push:
    branches: [main]

jobs:
  links:
    name: Check external links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: '.mlc-config.json'
